### ISSUE TITLE
Cache folders signed by original project name

### ISSUE THREAD

**Issue by FlightBlaze** [VenityStudio/Nearde-IDE#13]
### Cache folders signed by "DevelNext17" (original project name)  
**Where i found this bug:**  
C:\Users\\%username%\\.DevelNext17  
C:\Users\\%username%\\.DevelNext17.2018013112.SNAPSHOT  
_These two folders signed by original project name._  
**Solution:**
Rename them for example to ".NeardeIDE"

**Comment by MWGuy** [comment]
Ok
